In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [3]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


In [5]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\himanshu\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [6]:
tf.__version__

'2.17.0'

In [7]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [8]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
y = tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [10]:
z = tf.constant("India")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [11]:
s = tf.constant([3,2,1,4,5,6])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([3, 2, 1, 4, 5, 6])>

In [12]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
t_2d = tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [14]:
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
t_2d = tf.constant([1,2,3,4],shape=(2,2),dtype="int32")
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [16]:
t_3d_1 = tf.constant([[[1,2],[2,3],[3,4]]],dtype="float32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [17]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [18]:
t_3d_1.shape

TensorShape([1, 3, 2])

In [19]:
# Tensorflow Math Modules

In [20]:
import tensorflow as tf
import numpy as np

In [21]:
a = 10
b = 20
a+b

30

In [22]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [23]:
# Addition of Two List
l1 = [1,2,3,4]
l2 = [5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12])>

In [24]:
# Addition of Two Tuple
t1 = (2,3,4,5)
t2 = (5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13])>

In [25]:
l1 = [1,2,3,4]
a = 10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14])>

In [26]:
# Given a tensor x and y this operation x^y computers for corresponding elements in x and y.
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

In [27]:
# tf.math.abs
# real number
x = tf.constant([-2.25,3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [28]:
# complex number
x = tf.constant([[-2.25+4.75j],[-3.25+5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [29]:
# tf.math.subtract
x = [1,2,3,4,5]
y = 1
tf.subtract(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [31]:
x = [1,2,3,4]
y = 1
tf.subtract(y,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0, -1, -2, -3])>

In [32]:
# tf.math.Multiply
x = [1,2,3,4]
y = 2
tf.multiply(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8])>

In [33]:
# tf.math.multiply
import tensorflow as tf
x = tf.constant(([1,2,3,4]))
tf.math.multiply(x,2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8])>

In [34]:
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16])>

In [35]:
tf.math.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [36]:
x = tf.ones([1,2])
y = tf.ones([2,1])
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [37]:
# tf.math.maximum
x = tf.constant([0.,0.,0.,0.])
y = tf.constant([-2.,0.,2.,5.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [38]:
x = tf.constant([-5.,0.,0.,0.])
y = tf.constant([-3.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [39]:
# tf.math.minimum
x = tf.constant([0.,0.,0.,0.])
y = tf.constant([-5.,-2.,0.,3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [40]:
x = tf.constant([-5.,0.,0.,0.])
y = tf.constant([-3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [41]:
# tf.math.log
x = tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [42]:
# tf.math.divide
x = tf.constant([16,12,11])
y = tf.constant([4,6,2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [43]:
# tf.math.pow
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

In [44]:
# tf.math.sqrt
x = tf.constant([[4.0,],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [45]:
y = tf.constant([[-4.0],[16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [46]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [47]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [49]:
ones_2d = tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [50]:
ones_3d = tf.ones((2,2,4),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [51]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [52]:
zeros_2d = tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [2]:
# Tensorflow variable
# variable constructor requrires an initial value for the variable which can be a tensor of any type & shape.
# this initial value defines the type & shape of the variable.
# After construction the type & shape of the variable are fixed.

In [3]:
import tensorflow as tf

In [4]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [5]:
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [6]:
x.name

'Variable:0'

In [7]:
x.shape

TensorShape([4])

In [8]:
x.dtype

tf.int32

In [9]:
y = tf.Variable([1.0,2,3])

In [11]:
y = tf.Variable([1.0,2,3.3,4])
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [12]:
z = tf.Variable([True,False])
z

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [13]:
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [14]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
# create tensorflow Variable with different shape

In [17]:
t_2d = tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [18]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [19]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [20]:
# get index of highest value

In [21]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [22]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [23]:
# viewed/convert as a tensor

In [24]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [25]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [26]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [27]:
# change/Assing new value to tensor

In [28]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [30]:
x.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8])>

In [31]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8])>

In [32]:
# Assign variable with another memory

In [33]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 16])>

In [34]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 16])>

In [35]:
# placeholder-Migrate tensorflow 1 code to tensorflow2

In [36]:
import tensorflow as tf

In [37]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [38]:
tf.compat.v1.disable_eager_execution()

In [39]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [41]:
a = tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [42]:
b = tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_3:0' shape=(400, 400) dtype=float32>

In [43]:
c = tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [44]:
import numpy as np

In [45]:
ones_array = np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [46]:
with tf.compat.v1.Session() as sess:
    d = sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [47]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

In [48]:
# sparse tensor
# It enables efficient storage & processing of tensor that contains lot of zero values 

In [49]:
tf.SparseTensor()

TypeError: SparseTensor.__init__() missing 3 required positional arguments: 'indices', 'values', and 'dense_shape'

In [50]:
tf.SparseTensor(indices = [[0,3],[2,4]],values = [10,20],dense_shape=[3,10])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [51]:
st1  = tf.SparseTensor(indices = [[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [52]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))
